### ISSUE TITLE
Setup front end app with index and view query of O&G operators

### ISSUE THREAD

**Issue by brioux** [net-zero-project/blockchain-carbon-accounting#1]
Create node.js REACT app for oil and gas ESG portal. Put this in new directory (e.g., esg-portal) under app/

This simple app should expose index and view pages.

1. Index will provided a paginated list of organizations queried from POSTGRES database
2. View will list information about the divisions (e.g., states) they operate under, and information on the total number of assets they operate and their lat long coordinates.

Next we will work on integrate mapping plug-ins (e.g., arcgis) to show where these assets are located.
Late we will include division and assets level emission certificate statistics to the organization's view page.

**Comment by rose33-maker** [comment]
net-zero-project/blockchain-carbon-accounting#1

**Comment by rose33-maker** [comment]
How

**Comment by brioux** [comment]
@rose33-maker this was resolved several months ago. If you are interested in contributing I we can discuss opening a new for you to work on
